// Auto-generated. Do not edit!

// (in-package pet_robot_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class BreathingExerciseGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.exercise_type = null;
      this.duration_seconds = null;
    }
    else {
      if (initObj.hasOwnProperty('exercise_type')) {
        this.exercise_type = initObj.exercise_type
      }
      else {
        this.exercise_type = '';
      }
      if (initObj.hasOwnProperty('duration_seconds')) {
        this.duration_seconds = initObj.duration_seconds
      }
      else {
        this.duration_seconds = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type BreathingExerciseGoal
    // Serialize message field [exercise_type]
    bufferOffset = _serializer.string(obj.exercise_type, buffer, bufferOffset);
    // Serialize message field [duration_seconds]
    bufferOffset = _serializer.int32(obj.duration_seconds, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type BreathingExerciseGoal
    let len;
    let data = new BreathingExerciseGoal(null);
    // Deserialize message field [exercise_type]
    data.exercise_type = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [duration_seconds]
    data.duration_seconds = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.exercise_type.length;
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pet_robot_ros/BreathingExerciseGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a7ab7f891a004f4c0ba03e5137cfd00e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    string exercise_type  # box_breathing, deep_breathing, etc.
    int32 duration_seconds  # Total duration
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new BreathingExerciseGoal(null);
    if (msg.exercise_type !== undefined) {
      resolved.exercise_type = msg.exercise_type;
    }
    else {
      resolved.exercise_type = ''
    }

    if (msg.duration_seconds !== undefined) {
      resolved.duration_seconds = msg.duration_seconds;
    }
    else {
      resolved.duration_seconds = 0
    }

    return resolved;
    }
};

module.exports = BreathingExerciseGoal;
