// Auto-generated. Do not edit!

// (in-package pet_robot_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let BreathingExerciseActionGoal = require('./BreathingExerciseActionGoal.js');
let BreathingExerciseActionResult = require('./BreathingExerciseActionResult.js');
let BreathingExerciseActionFeedback = require('./BreathingExerciseActionFeedback.js');

//-----------------------------------------------------------

class BreathingExerciseAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new BreathingExerciseActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new BreathingExerciseActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new BreathingExerciseActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type BreathingExerciseAction
    // Serialize message field [action_goal]
    bufferOffset = BreathingExerciseActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = BreathingExerciseActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = BreathingExerciseActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type BreathingExerciseAction
    let len;
    let data = new BreathingExerciseAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = BreathingExerciseActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = BreathingExerciseActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = BreathingExerciseActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += BreathingExerciseActionGoal.getMessageSize(object.action_goal);
    length += BreathingExerciseActionResult.getMessageSize(object.action_result);
    length += BreathingExerciseActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pet_robot_ros/BreathingExerciseAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b6e7d1c31b4282df50f4b4b7afaaa072';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    BreathingExerciseActionGoal action_goal
    BreathingExerciseActionResult action_result
    BreathingExerciseActionFeedback action_feedback
    
    ================================================================================
    MSG: pet_robot_ros/BreathingExerciseActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    BreathingExerciseGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: pet_robot_ros/BreathingExerciseGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    string exercise_type  # box_breathing, deep_breathing, etc.
    int32 duration_seconds  # Total duration
    
    ================================================================================
    MSG: pet_robot_ros/BreathingExerciseActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    BreathingExerciseResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: pet_robot_ros/BreathingExerciseResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    bool completed
    string message
    
    ================================================================================
    MSG: pet_robot_ros/BreathingExerciseActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    BreathingExerciseFeedback feedback
    
    ================================================================================
    MSG: pet_robot_ros/BreathingExerciseFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    int32 current_step  # Current step in exercise
    string instruction  # Current instruction
    float32 progress  # 0.0 to 1.0
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new BreathingExerciseAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = BreathingExerciseActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new BreathingExerciseActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = BreathingExerciseActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new BreathingExerciseActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = BreathingExerciseActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new BreathingExerciseActionFeedback()
    }

    return resolved;
    }
};

module.exports = BreathingExerciseAction;
