(cl:defpackage pet_robot_ros-msg
  (:use )
  (:export
   "<BREATHINGEXERCISEACTION>"
   "BREATHINGEXERCISEACTION"
   "<BREATHINGEXERCISEACTIONFEEDBACK>"
   "BREATHINGEXERCISEACTIONFEEDBACK"
   "<BREATHINGEXERCISEACTIONGOAL>"
   "BREATHINGEXERCISEACTIONGOAL"
   "<BREATHINGEXERCISEACTIONRESULT>"
   "BREATHINGEXERCISEACTIONRESULT"
   "<BREATHINGEXERCISEFEEDBACK>"
   "BREATHINGEXERCISEFEEDBACK"
   "<BREATHINGEXERCISEGOAL>"
   "BREATHINGEXERCISEGOAL"
   "<BREATHINGEXERCISERESULT>"
   "BREATHINGEXERCISERESULT"
   "<EMOTION>"
   "EMOTION"
   "<MOODLOG>"
   "MOODLOG"
   "<ROBOTSTATE>"
   "ROBOTSTATE"
   "<SENSORDATA>"
   "SENSORDATA"
  ))

