; Auto-generated. Do not edit!


(cl:in-package pet_robot_ros-msg)


;//! \htmlinclude BreathingExerciseActionGoal.msg.html

(cl:defclass <BreathingExerciseActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type pet_robot_ros-msg:BreathingExerciseGoal
    :initform (cl:make-instance 'pet_robot_ros-msg:BreathingExerciseGoal)))
)

(cl:defclass BreathingExerciseActionGoal (<BreathingExerciseActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BreathingExerciseActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BreathingExerciseActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pet_robot_ros-msg:<BreathingExerciseActionGoal> is deprecated: use pet_robot_ros-msg:BreathingExerciseActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <BreathingExerciseActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pet_robot_ros-msg:header-val is deprecated.  Use pet_robot_ros-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <BreathingExerciseActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pet_robot_ros-msg:goal_id-val is deprecated.  Use pet_robot_ros-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <BreathingExerciseActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pet_robot_ros-msg:goal-val is deprecated.  Use pet_robot_ros-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BreathingExerciseActionGoal>) ostream)
  "Serializes a message object of type '<BreathingExerciseActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BreathingExerciseActionGoal>) istream)
  "Deserializes a message object of type '<BreathingExerciseActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BreathingExerciseActionGoal>)))
  "Returns string type for a message object of type '<BreathingExerciseActionGoal>"
  "pet_robot_ros/BreathingExerciseActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BreathingExerciseActionGoal)))
  "Returns string type for a message object of type 'BreathingExerciseActionGoal"
  "pet_robot_ros/BreathingExerciseActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BreathingExerciseActionGoal>)))
  "Returns md5sum for a message object of type '<BreathingExerciseActionGoal>"
  "9d0dbbfa163f04592b1dd5fc1442f2b7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BreathingExerciseActionGoal)))
  "Returns md5sum for a message object of type 'BreathingExerciseActionGoal"
  "9d0dbbfa163f04592b1dd5fc1442f2b7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BreathingExerciseActionGoal>)))
  "Returns full string definition for message of type '<BreathingExerciseActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%BreathingExerciseGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: pet_robot_ros/BreathingExerciseGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string exercise_type  # box_breathing, deep_breathing, etc.~%int32 duration_seconds  # Total duration~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BreathingExerciseActionGoal)))
  "Returns full string definition for message of type 'BreathingExerciseActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%BreathingExerciseGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: pet_robot_ros/BreathingExerciseGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string exercise_type  # box_breathing, deep_breathing, etc.~%int32 duration_seconds  # Total duration~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BreathingExerciseActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BreathingExerciseActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'BreathingExerciseActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
