; Auto-generated. Do not edit!


(cl:in-package pet_robot_ros-msg)


;//! \htmlinclude BreathingExerciseGoal.msg.html

(cl:defclass <BreathingExerciseGoal> (roslisp-msg-protocol:ros-message)
  ((exercise_type
    :reader exercise_type
    :initarg :exercise_type
    :type cl:string
    :initform "")
   (duration_seconds
    :reader duration_seconds
    :initarg :duration_seconds
    :type cl:integer
    :initform 0))
)

(cl:defclass BreathingExerciseGoal (<BreathingExerciseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BreathingExerciseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BreathingExerciseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pet_robot_ros-msg:<BreathingExerciseGoal> is deprecated: use pet_robot_ros-msg:BreathingExerciseGoal instead.")))

(cl:ensure-generic-function 'exercise_type-val :lambda-list '(m))
(cl:defmethod exercise_type-val ((m <BreathingExerciseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pet_robot_ros-msg:exercise_type-val is deprecated.  Use pet_robot_ros-msg:exercise_type instead.")
  (exercise_type m))

(cl:ensure-generic-function 'duration_seconds-val :lambda-list '(m))
(cl:defmethod duration_seconds-val ((m <BreathingExerciseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pet_robot_ros-msg:duration_seconds-val is deprecated.  Use pet_robot_ros-msg:duration_seconds instead.")
  (duration_seconds m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BreathingExerciseGoal>) ostream)
  "Serializes a message object of type '<BreathingExerciseGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'exercise_type))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'exercise_type))
  (cl:let* ((signed (cl:slot-value msg 'duration_seconds)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BreathingExerciseGoal>) istream)
  "Deserializes a message object of type '<BreathingExerciseGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'exercise_type) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'exercise_type) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'duration_seconds) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BreathingExerciseGoal>)))
  "Returns string type for a message object of type '<BreathingExerciseGoal>"
  "pet_robot_ros/BreathingExerciseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BreathingExerciseGoal)))
  "Returns string type for a message object of type 'BreathingExerciseGoal"
  "pet_robot_ros/BreathingExerciseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BreathingExerciseGoal>)))
  "Returns md5sum for a message object of type '<BreathingExerciseGoal>"
  "a7ab7f891a004f4c0ba03e5137cfd00e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BreathingExerciseGoal)))
  "Returns md5sum for a message object of type 'BreathingExerciseGoal"
  "a7ab7f891a004f4c0ba03e5137cfd00e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BreathingExerciseGoal>)))
  "Returns full string definition for message of type '<BreathingExerciseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string exercise_type  # box_breathing, deep_breathing, etc.~%int32 duration_seconds  # Total duration~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BreathingExerciseGoal)))
  "Returns full string definition for message of type 'BreathingExerciseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string exercise_type  # box_breathing, deep_breathing, etc.~%int32 duration_seconds  # Total duration~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BreathingExerciseGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'exercise_type))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BreathingExerciseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'BreathingExerciseGoal
    (cl:cons ':exercise_type (exercise_type msg))
    (cl:cons ':duration_seconds (duration_seconds msg))
))
