; Auto-generated. Do not edit!


(cl:in-package pet_robot_ros-msg)


;//! \htmlinclude BreathingExerciseResult.msg.html

(cl:defclass <BreathingExerciseResult> (roslisp-msg-protocol:ros-message)
  ((completed
    :reader completed
    :initarg :completed
    :type cl:boolean
    :initform cl:nil)
   (message
    :reader message
    :initarg :message
    :type cl:string
    :initform ""))
)

(cl:defclass BreathingExerciseResult (<BreathingExerciseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BreathingExerciseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BreathingExerciseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pet_robot_ros-msg:<BreathingExerciseResult> is deprecated: use pet_robot_ros-msg:BreathingExerciseResult instead.")))

(cl:ensure-generic-function 'completed-val :lambda-list '(m))
(cl:defmethod completed-val ((m <BreathingExerciseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pet_robot_ros-msg:completed-val is deprecated.  Use pet_robot_ros-msg:completed instead.")
  (completed m))

(cl:ensure-generic-function 'message-val :lambda-list '(m))
(cl:defmethod message-val ((m <BreathingExerciseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pet_robot_ros-msg:message-val is deprecated.  Use pet_robot_ros-msg:message instead.")
  (message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BreathingExerciseResult>) ostream)
  "Serializes a message object of type '<BreathingExerciseResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'completed) 1 0)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BreathingExerciseResult>) istream)
  "Deserializes a message object of type '<BreathingExerciseResult>"
    (cl:setf (cl:slot-value msg 'completed) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BreathingExerciseResult>)))
  "Returns string type for a message object of type '<BreathingExerciseResult>"
  "pet_robot_ros/BreathingExerciseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BreathingExerciseResult)))
  "Returns string type for a message object of type 'BreathingExerciseResult"
  "pet_robot_ros/BreathingExerciseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BreathingExerciseResult>)))
  "Returns md5sum for a message object of type '<BreathingExerciseResult>"
  "19e4d489fc842d87d6fb2d321a20a69e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BreathingExerciseResult)))
  "Returns md5sum for a message object of type 'BreathingExerciseResult"
  "19e4d489fc842d87d6fb2d321a20a69e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BreathingExerciseResult>)))
  "Returns full string definition for message of type '<BreathingExerciseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool completed~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BreathingExerciseResult)))
  "Returns full string definition for message of type 'BreathingExerciseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool completed~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BreathingExerciseResult>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BreathingExerciseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'BreathingExerciseResult
    (cl:cons ':completed (completed msg))
    (cl:cons ':message (message msg))
))
