(cl:defpackage pet_robot_ros-srv
  (:use )
  (:export
   "GETAFFIRMATION"
   "<GETAFFIRMATION-REQUEST>"
   "GETAFFIRMATION-REQUEST"
   "<GETAFFIRMATION-RESPONSE>"
   "GETAFFIRMATION-RESPONSE"
   "LOGMOOD"
   "<LOGMOOD-REQUEST>"
   "LOGMOOD-REQUEST"
   "<LOGMOOD-RESPONSE>"
   "LOGMOOD-RESPONSE"
   "SETEMOTION"
   "<SETEMOTION-REQUEST>"
   "SETEMOTION-REQUEST"
   "<SETEMOTION-RESPONSE>"
   "SETEMOTION-RESPONSE"
  ))

