// Generated by gencpp from file pet_robot_ros/BreathingExerciseGoal.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_BREATHINGEXERCISEGOAL_H
#define PET_ROBOT_ROS_MESSAGE_BREATHINGEXERCISEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pet_robot_ros
{
template <class ContainerAllocator>
struct BreathingExerciseGoal_
{
  typedef BreathingExerciseGoal_<ContainerAllocator> Type;

  BreathingExerciseGoal_()
    : exercise_type()
    , duration_seconds(0)  {
    }
  BreathingExerciseGoal_(const ContainerAllocator& _alloc)
    : exercise_type(_alloc)
    , duration_seconds(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _exercise_type_type;
  _exercise_type_type exercise_type;

   typedef int32_t _duration_seconds_type;
  _duration_seconds_type duration_seconds;





  typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> const> ConstPtr;

}; // struct BreathingExerciseGoal_

typedef ::pet_robot_ros::BreathingExerciseGoal_<std::allocator<void> > BreathingExerciseGoal;

typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseGoal > BreathingExerciseGoalPtr;
typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseGoal const> BreathingExerciseGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator1> & lhs, const ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator2> & rhs)
{
  return lhs.exercise_type == rhs.exercise_type &&
    lhs.duration_seconds == rhs.duration_seconds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator1> & lhs, const ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7ab7f891a004f4c0ba03e5137cfd00e";
  }

  static const char* value(const ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7ab7f891a004f4cULL;
  static const uint64_t static_value2 = 0x0ba03e5137cfd00eULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/BreathingExerciseGoal";
  }

  static const char* value(const ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"string exercise_type  # box_breathing, deep_breathing, etc.\n"
"int32 duration_seconds  # Total duration\n"
;
  }

  static const char* value(const ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.exercise_type);
      stream.next(m.duration_seconds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BreathingExerciseGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pet_robot_ros::BreathingExerciseGoal_<ContainerAllocator>& v)
  {
    s << indent << "exercise_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.exercise_type);
    s << indent << "duration_seconds: ";
    Printer<int32_t>::stream(s, indent + "  ", v.duration_seconds);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_BREATHINGEXERCISEGOAL_H
