// Generated by gencpp from file pet_robot_ros/BreathingExerciseResult.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_BREATHINGEXERCISERESULT_H
#define PET_ROBOT_ROS_MESSAGE_BREATHINGEXERCISERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pet_robot_ros
{
template <class ContainerAllocator>
struct BreathingExerciseResult_
{
  typedef BreathingExerciseResult_<ContainerAllocator> Type;

  BreathingExerciseResult_()
    : completed(false)
    , message()  {
    }
  BreathingExerciseResult_(const ContainerAllocator& _alloc)
    : completed(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _completed_type;
  _completed_type completed;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> const> ConstPtr;

}; // struct BreathingExerciseResult_

typedef ::pet_robot_ros::BreathingExerciseResult_<std::allocator<void> > BreathingExerciseResult;

typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseResult > BreathingExerciseResultPtr;
typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseResult const> BreathingExerciseResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator1> & lhs, const ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator2> & rhs)
{
  return lhs.completed == rhs.completed &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator1> & lhs, const ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19e4d489fc842d87d6fb2d321a20a69e";
  }

  static const char* value(const ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19e4d489fc842d87ULL;
  static const uint64_t static_value2 = 0xd6fb2d321a20a69eULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/BreathingExerciseResult";
  }

  static const char* value(const ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"bool completed\n"
"string message\n"
;
  }

  static const char* value(const ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.completed);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BreathingExerciseResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pet_robot_ros::BreathingExerciseResult_<ContainerAllocator>& v)
  {
    s << indent << "completed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.completed);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_BREATHINGEXERCISERESULT_H
