// Generated by gencpp from file pet_robot_ros/BreathingExerciseFeedback.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_BREATHINGEXERCISEFEEDBACK_H
#define PET_ROBOT_ROS_MESSAGE_BREATHINGEXERCISEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pet_robot_ros
{
template <class ContainerAllocator>
struct BreathingExerciseFeedback_
{
  typedef BreathingExerciseFeedback_<ContainerAllocator> Type;

  BreathingExerciseFeedback_()
    : current_step(0)
    , instruction()
    , progress(0.0)  {
    }
  BreathingExerciseFeedback_(const ContainerAllocator& _alloc)
    : current_step(0)
    , instruction(_alloc)
    , progress(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _current_step_type;
  _current_step_type current_step;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _instruction_type;
  _instruction_type instruction;

   typedef float _progress_type;
  _progress_type progress;





  typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct BreathingExerciseFeedback_

typedef ::pet_robot_ros::BreathingExerciseFeedback_<std::allocator<void> > BreathingExerciseFeedback;

typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseFeedback > BreathingExerciseFeedbackPtr;
typedef boost::shared_ptr< ::pet_robot_ros::BreathingExerciseFeedback const> BreathingExerciseFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator1> & lhs, const ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_step == rhs.current_step &&
    lhs.instruction == rhs.instruction &&
    lhs.progress == rhs.progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator1> & lhs, const ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "435a434729139d5d8aed2b71a0790f17";
  }

  static const char* value(const ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x435a434729139d5dULL;
  static const uint64_t static_value2 = 0x8aed2b71a0790f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/BreathingExerciseFeedback";
  }

  static const char* value(const ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"int32 current_step  # Current step in exercise\n"
"string instruction  # Current instruction\n"
"float32 progress  # 0.0 to 1.0\n"
"\n"
;
  }

  static const char* value(const ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_step);
      stream.next(m.instruction);
      stream.next(m.progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BreathingExerciseFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pet_robot_ros::BreathingExerciseFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_step: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_step);
    s << indent << "instruction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.instruction);
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_BREATHINGEXERCISEFEEDBACK_H
