// Generated by gencpp from file pet_robot_ros/Emotion.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_EMOTION_H
#define PET_ROBOT_ROS_MESSAGE_EMOTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pet_robot_ros
{
template <class ContainerAllocator>
struct Emotion_
{
  typedef Emotion_<ContainerAllocator> Type;

  Emotion_()
    : emotion()
    , intensity(0.0)
    , timestamp()  {
    }
  Emotion_(const ContainerAllocator& _alloc)
    : emotion(_alloc)
    , intensity(0.0)
    , timestamp()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _emotion_type;
  _emotion_type emotion;

   typedef float _intensity_type;
  _intensity_type intensity;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::pet_robot_ros::Emotion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::Emotion_<ContainerAllocator> const> ConstPtr;

}; // struct Emotion_

typedef ::pet_robot_ros::Emotion_<std::allocator<void> > Emotion;

typedef boost::shared_ptr< ::pet_robot_ros::Emotion > EmotionPtr;
typedef boost::shared_ptr< ::pet_robot_ros::Emotion const> EmotionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::Emotion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::Emotion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pet_robot_ros::Emotion_<ContainerAllocator1> & lhs, const ::pet_robot_ros::Emotion_<ContainerAllocator2> & rhs)
{
  return lhs.emotion == rhs.emotion &&
    lhs.intensity == rhs.intensity &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pet_robot_ros::Emotion_<ContainerAllocator1> & lhs, const ::pet_robot_ros::Emotion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::Emotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::Emotion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::Emotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::Emotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::Emotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::Emotion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::Emotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7af84fb54cd74beec900c75b72aa6ef";
  }

  static const char* value(const ::pet_robot_ros::Emotion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7af84fb54cd74beULL;
  static const uint64_t static_value2 = 0xec900c75b72aa6efULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::Emotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/Emotion";
  }

  static const char* value(const ::pet_robot_ros::Emotion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::Emotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Emotion message for robot's current emotional state\n"
"string emotion  # happy, sad, anxious, stressed, tired, angry, neutral, crisis\n"
"float32 intensity  # 0.0 to 1.0\n"
"time timestamp\n"
;
  }

  static const char* value(const ::pet_robot_ros::Emotion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::Emotion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.emotion);
      stream.next(m.intensity);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Emotion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::Emotion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pet_robot_ros::Emotion_<ContainerAllocator>& v)
  {
    s << indent << "emotion: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.emotion);
    s << indent << "intensity: ";
    Printer<float>::stream(s, indent + "  ", v.intensity);
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_EMOTION_H
