// Generated by gencpp from file pet_robot_ros/GetAffirmationResponse.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_GETAFFIRMATIONRESPONSE_H
#define PET_ROBOT_ROS_MESSAGE_GETAFFIRMATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pet_robot_ros
{
template <class ContainerAllocator>
struct GetAffirmationResponse_
{
  typedef GetAffirmationResponse_<ContainerAllocator> Type;

  GetAffirmationResponse_()
    : affirmation()
    , timestamp()  {
    }
  GetAffirmationResponse_(const ContainerAllocator& _alloc)
    : affirmation(_alloc)
    , timestamp()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _affirmation_type;
  _affirmation_type affirmation;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAffirmationResponse_

typedef ::pet_robot_ros::GetAffirmationResponse_<std::allocator<void> > GetAffirmationResponse;

typedef boost::shared_ptr< ::pet_robot_ros::GetAffirmationResponse > GetAffirmationResponsePtr;
typedef boost::shared_ptr< ::pet_robot_ros::GetAffirmationResponse const> GetAffirmationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator1> & lhs, const ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.affirmation == rhs.affirmation &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator1> & lhs, const ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "176b3ebe98603e26ffc647c2f65b7d30";
  }

  static const char* value(const ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x176b3ebe98603e26ULL;
  static const uint64_t static_value2 = 0xffc647c2f65b7d30ULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/GetAffirmationResponse";
  }

  static const char* value(const ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"string affirmation\n"
"time timestamp\n"
"\n"
;
  }

  static const char* value(const ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.affirmation);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAffirmationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pet_robot_ros::GetAffirmationResponse_<ContainerAllocator>& v)
  {
    s << indent << "affirmation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.affirmation);
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_GETAFFIRMATIONRESPONSE_H
