// Generated by gencpp from file pet_robot_ros/GetAffirmation.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_GETAFFIRMATION_H
#define PET_ROBOT_ROS_MESSAGE_GETAFFIRMATION_H

#include <ros/service_traits.h>


#include <pet_robot_ros/GetAffirmationRequest.h>
#include <pet_robot_ros/GetAffirmationResponse.h>


namespace pet_robot_ros
{

struct GetAffirmation
{

typedef GetAffirmationRequest Request;
typedef GetAffirmationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAffirmation
} // namespace pet_robot_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pet_robot_ros::GetAffirmation > {
  static const char* value()
  {
    return "176b3ebe98603e26ffc647c2f65b7d30";
  }

  static const char* value(const ::pet_robot_ros::GetAffirmation&) { return value(); }
};

template<>
struct DataType< ::pet_robot_ros::GetAffirmation > {
  static const char* value()
  {
    return "pet_robot_ros/GetAffirmation";
  }

  static const char* value(const ::pet_robot_ros::GetAffirmation&) { return value(); }
};


// service_traits::MD5Sum< ::pet_robot_ros::GetAffirmationRequest> should match
// service_traits::MD5Sum< ::pet_robot_ros::GetAffirmation >
template<>
struct MD5Sum< ::pet_robot_ros::GetAffirmationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pet_robot_ros::GetAffirmation >::value();
  }
  static const char* value(const ::pet_robot_ros::GetAffirmationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pet_robot_ros::GetAffirmationRequest> should match
// service_traits::DataType< ::pet_robot_ros::GetAffirmation >
template<>
struct DataType< ::pet_robot_ros::GetAffirmationRequest>
{
  static const char* value()
  {
    return DataType< ::pet_robot_ros::GetAffirmation >::value();
  }
  static const char* value(const ::pet_robot_ros::GetAffirmationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pet_robot_ros::GetAffirmationResponse> should match
// service_traits::MD5Sum< ::pet_robot_ros::GetAffirmation >
template<>
struct MD5Sum< ::pet_robot_ros::GetAffirmationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pet_robot_ros::GetAffirmation >::value();
  }
  static const char* value(const ::pet_robot_ros::GetAffirmationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pet_robot_ros::GetAffirmationResponse> should match
// service_traits::DataType< ::pet_robot_ros::GetAffirmation >
template<>
struct DataType< ::pet_robot_ros::GetAffirmationResponse>
{
  static const char* value()
  {
    return DataType< ::pet_robot_ros::GetAffirmation >::value();
  }
  static const char* value(const ::pet_robot_ros::GetAffirmationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_GETAFFIRMATION_H
