// Generated by gencpp from file pet_robot_ros/GetAffirmationRequest.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_GETAFFIRMATIONREQUEST_H
#define PET_ROBOT_ROS_MESSAGE_GETAFFIRMATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pet_robot_ros
{
template <class ContainerAllocator>
struct GetAffirmationRequest_
{
  typedef GetAffirmationRequest_<ContainerAllocator> Type;

  GetAffirmationRequest_()
    {
    }
  GetAffirmationRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetAffirmationRequest_

typedef ::pet_robot_ros::GetAffirmationRequest_<std::allocator<void> > GetAffirmationRequest;

typedef boost::shared_ptr< ::pet_robot_ros::GetAffirmationRequest > GetAffirmationRequestPtr;
typedef boost::shared_ptr< ::pet_robot_ros::GetAffirmationRequest const> GetAffirmationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/GetAffirmationRequest";
  }

  static const char* value(const ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request a positive affirmation\n"
;
  }

  static const char* value(const ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAffirmationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pet_robot_ros::GetAffirmationRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_GETAFFIRMATIONREQUEST_H
