// Generated by gencpp from file pet_robot_ros/LogMoodResponse.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_LOGMOODRESPONSE_H
#define PET_ROBOT_ROS_MESSAGE_LOGMOODRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pet_robot_ros
{
template <class ContainerAllocator>
struct LogMoodResponse_
{
  typedef LogMoodResponse_<ContainerAllocator> Type;

  LogMoodResponse_()
    : success(false)
    , response()
    , suggestions()  {
    }
  LogMoodResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , response(_alloc)
    , suggestions(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _suggestions_type;
  _suggestions_type suggestions;





  typedef boost::shared_ptr< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LogMoodResponse_

typedef ::pet_robot_ros::LogMoodResponse_<std::allocator<void> > LogMoodResponse;

typedef boost::shared_ptr< ::pet_robot_ros::LogMoodResponse > LogMoodResponsePtr;
typedef boost::shared_ptr< ::pet_robot_ros::LogMoodResponse const> LogMoodResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pet_robot_ros::LogMoodResponse_<ContainerAllocator1> & lhs, const ::pet_robot_ros::LogMoodResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.response == rhs.response &&
    lhs.suggestions == rhs.suggestions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pet_robot_ros::LogMoodResponse_<ContainerAllocator1> & lhs, const ::pet_robot_ros::LogMoodResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2981315bcdd00a3184bc6d2282ec1f55";
  }

  static const char* value(const ::pet_robot_ros::LogMoodResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2981315bcdd00a31ULL;
  static const uint64_t static_value2 = 0x84bc6d2282ec1f55ULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/LogMoodResponse";
  }

  static const char* value(const ::pet_robot_ros::LogMoodResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"bool success\n"
"string response  # Supportive response from robot\n"
"string[] suggestions  # Suggested coping activities\n"
"\n"
;
  }

  static const char* value(const ::pet_robot_ros::LogMoodResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.response);
      stream.next(m.suggestions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LogMoodResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::LogMoodResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pet_robot_ros::LogMoodResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
    s << indent << "suggestions[]" << std::endl;
    for (size_t i = 0; i < v.suggestions.size(); ++i)
    {
      s << indent << "  suggestions[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.suggestions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_LOGMOODRESPONSE_H
