// Generated by gencpp from file pet_robot_ros/LogMood.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_LOGMOOD_H
#define PET_ROBOT_ROS_MESSAGE_LOGMOOD_H

#include <ros/service_traits.h>


#include <pet_robot_ros/LogMoodRequest.h>
#include <pet_robot_ros/LogMoodResponse.h>


namespace pet_robot_ros
{

struct LogMood
{

typedef LogMoodRequest Request;
typedef LogMoodResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LogMood
} // namespace pet_robot_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pet_robot_ros::LogMood > {
  static const char* value()
  {
    return "b43c763a2a7bf67b61c6235ef921779c";
  }

  static const char* value(const ::pet_robot_ros::LogMood&) { return value(); }
};

template<>
struct DataType< ::pet_robot_ros::LogMood > {
  static const char* value()
  {
    return "pet_robot_ros/LogMood";
  }

  static const char* value(const ::pet_robot_ros::LogMood&) { return value(); }
};


// service_traits::MD5Sum< ::pet_robot_ros::LogMoodRequest> should match
// service_traits::MD5Sum< ::pet_robot_ros::LogMood >
template<>
struct MD5Sum< ::pet_robot_ros::LogMoodRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pet_robot_ros::LogMood >::value();
  }
  static const char* value(const ::pet_robot_ros::LogMoodRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pet_robot_ros::LogMoodRequest> should match
// service_traits::DataType< ::pet_robot_ros::LogMood >
template<>
struct DataType< ::pet_robot_ros::LogMoodRequest>
{
  static const char* value()
  {
    return DataType< ::pet_robot_ros::LogMood >::value();
  }
  static const char* value(const ::pet_robot_ros::LogMoodRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pet_robot_ros::LogMoodResponse> should match
// service_traits::MD5Sum< ::pet_robot_ros::LogMood >
template<>
struct MD5Sum< ::pet_robot_ros::LogMoodResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pet_robot_ros::LogMood >::value();
  }
  static const char* value(const ::pet_robot_ros::LogMoodResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pet_robot_ros::LogMoodResponse> should match
// service_traits::DataType< ::pet_robot_ros::LogMood >
template<>
struct DataType< ::pet_robot_ros::LogMoodResponse>
{
  static const char* value()
  {
    return DataType< ::pet_robot_ros::LogMood >::value();
  }
  static const char* value(const ::pet_robot_ros::LogMoodResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_LOGMOOD_H
