// Generated by gencpp from file pet_robot_ros/MoodLog.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_MOODLOG_H
#define PET_ROBOT_ROS_MESSAGE_MOODLOG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pet_robot_ros
{
template <class ContainerAllocator>
struct MoodLog_
{
  typedef MoodLog_<ContainerAllocator> Type;

  MoodLog_()
    : mood()
    , intensity(0)
    , notes()
    , timestamp()  {
    }
  MoodLog_(const ContainerAllocator& _alloc)
    : mood(_alloc)
    , intensity(0)
    , notes(_alloc)
    , timestamp()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mood_type;
  _mood_type mood;

   typedef int32_t _intensity_type;
  _intensity_type intensity;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _notes_type;
  _notes_type notes;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::pet_robot_ros::MoodLog_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::MoodLog_<ContainerAllocator> const> ConstPtr;

}; // struct MoodLog_

typedef ::pet_robot_ros::MoodLog_<std::allocator<void> > MoodLog;

typedef boost::shared_ptr< ::pet_robot_ros::MoodLog > MoodLogPtr;
typedef boost::shared_ptr< ::pet_robot_ros::MoodLog const> MoodLogConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::MoodLog_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::MoodLog_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pet_robot_ros::MoodLog_<ContainerAllocator1> & lhs, const ::pet_robot_ros::MoodLog_<ContainerAllocator2> & rhs)
{
  return lhs.mood == rhs.mood &&
    lhs.intensity == rhs.intensity &&
    lhs.notes == rhs.notes &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pet_robot_ros::MoodLog_<ContainerAllocator1> & lhs, const ::pet_robot_ros::MoodLog_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::MoodLog_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::MoodLog_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::MoodLog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::MoodLog_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::MoodLog_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::MoodLog_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::MoodLog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4584f6b7d371bdba788c5cd148510811";
  }

  static const char* value(const ::pet_robot_ros::MoodLog_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4584f6b7d371bdbaULL;
  static const uint64_t static_value2 = 0x788c5cd148510811ULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::MoodLog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/MoodLog";
  }

  static const char* value(const ::pet_robot_ros::MoodLog_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::MoodLog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Mood log entry for mental health tracking\n"
"string mood  # anxious, sad, happy, stressed, tired, angry, neutral\n"
"int32 intensity  # 1-10 scale\n"
"string notes\n"
"time timestamp\n"
;
  }

  static const char* value(const ::pet_robot_ros::MoodLog_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::MoodLog_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mood);
      stream.next(m.intensity);
      stream.next(m.notes);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoodLog_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::MoodLog_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pet_robot_ros::MoodLog_<ContainerAllocator>& v)
  {
    s << indent << "mood: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mood);
    s << indent << "intensity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.intensity);
    s << indent << "notes: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.notes);
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_MOODLOG_H
