// Generated by gencpp from file pet_robot_ros/RobotState.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_ROBOTSTATE_H
#define PET_ROBOT_ROS_MESSAGE_ROBOTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pet_robot_ros/Emotion.h>
#include <pet_robot_ros/SensorData.h>

namespace pet_robot_ros
{
template <class ContainerAllocator>
struct RobotState_
{
  typedef RobotState_<ContainerAllocator> Type;

  RobotState_()
    : emotion()
    , is_speaking(false)
    , is_listening(false)
    , battery_level(0)
    , sensor_data()  {
    }
  RobotState_(const ContainerAllocator& _alloc)
    : emotion(_alloc)
    , is_speaking(false)
    , is_listening(false)
    , battery_level(0)
    , sensor_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::pet_robot_ros::Emotion_<ContainerAllocator>  _emotion_type;
  _emotion_type emotion;

   typedef uint8_t _is_speaking_type;
  _is_speaking_type is_speaking;

   typedef uint8_t _is_listening_type;
  _is_listening_type is_listening;

   typedef int32_t _battery_level_type;
  _battery_level_type battery_level;

   typedef  ::pet_robot_ros::SensorData_<ContainerAllocator>  _sensor_data_type;
  _sensor_data_type sensor_data;





  typedef boost::shared_ptr< ::pet_robot_ros::RobotState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::RobotState_<ContainerAllocator> const> ConstPtr;

}; // struct RobotState_

typedef ::pet_robot_ros::RobotState_<std::allocator<void> > RobotState;

typedef boost::shared_ptr< ::pet_robot_ros::RobotState > RobotStatePtr;
typedef boost::shared_ptr< ::pet_robot_ros::RobotState const> RobotStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::RobotState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::RobotState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pet_robot_ros::RobotState_<ContainerAllocator1> & lhs, const ::pet_robot_ros::RobotState_<ContainerAllocator2> & rhs)
{
  return lhs.emotion == rhs.emotion &&
    lhs.is_speaking == rhs.is_speaking &&
    lhs.is_listening == rhs.is_listening &&
    lhs.battery_level == rhs.battery_level &&
    lhs.sensor_data == rhs.sensor_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pet_robot_ros::RobotState_<ContainerAllocator1> & lhs, const ::pet_robot_ros::RobotState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::RobotState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::RobotState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::RobotState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23f43ffc60bb2cce618de7427a61ab01";
  }

  static const char* value(const ::pet_robot_ros::RobotState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23f43ffc60bb2cceULL;
  static const uint64_t static_value2 = 0x618de7427a61ab01ULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/RobotState";
  }

  static const char* value(const ::pet_robot_ros::RobotState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Complete robot state\n"
"Emotion emotion\n"
"bool is_speaking\n"
"bool is_listening\n"
"int32 battery_level  # 0-100\n"
"SensorData sensor_data\n"
"\n"
"================================================================================\n"
"MSG: pet_robot_ros/Emotion\n"
"# Emotion message for robot's current emotional state\n"
"string emotion  # happy, sad, anxious, stressed, tired, angry, neutral, crisis\n"
"float32 intensity  # 0.0 to 1.0\n"
"time timestamp\n"
"\n"
"================================================================================\n"
"MSG: pet_robot_ros/SensorData\n"
"# Sensor data from robot\n"
"bool touch_detected\n"
"float32 distance  # cm\n"
"float32 temperature  # Celsius\n"
"time timestamp\n"
;
  }

  static const char* value(const ::pet_robot_ros::RobotState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::RobotState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.emotion);
      stream.next(m.is_speaking);
      stream.next(m.is_listening);
      stream.next(m.battery_level);
      stream.next(m.sensor_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::RobotState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pet_robot_ros::RobotState_<ContainerAllocator>& v)
  {
    s << indent << "emotion: ";
    s << std::endl;
    Printer< ::pet_robot_ros::Emotion_<ContainerAllocator> >::stream(s, indent + "  ", v.emotion);
    s << indent << "is_speaking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_speaking);
    s << indent << "is_listening: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_listening);
    s << indent << "battery_level: ";
    Printer<int32_t>::stream(s, indent + "  ", v.battery_level);
    s << indent << "sensor_data: ";
    s << std::endl;
    Printer< ::pet_robot_ros::SensorData_<ContainerAllocator> >::stream(s, indent + "  ", v.sensor_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_ROBOTSTATE_H
