// Generated by gencpp from file pet_robot_ros/SensorData.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_SENSORDATA_H
#define PET_ROBOT_ROS_MESSAGE_SENSORDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pet_robot_ros
{
template <class ContainerAllocator>
struct SensorData_
{
  typedef SensorData_<ContainerAllocator> Type;

  SensorData_()
    : touch_detected(false)
    , distance(0.0)
    , temperature(0.0)
    , timestamp()  {
    }
  SensorData_(const ContainerAllocator& _alloc)
    : touch_detected(false)
    , distance(0.0)
    , temperature(0.0)
    , timestamp()  {
  (void)_alloc;
    }



   typedef uint8_t _touch_detected_type;
  _touch_detected_type touch_detected;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _temperature_type;
  _temperature_type temperature;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::pet_robot_ros::SensorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::SensorData_<ContainerAllocator> const> ConstPtr;

}; // struct SensorData_

typedef ::pet_robot_ros::SensorData_<std::allocator<void> > SensorData;

typedef boost::shared_ptr< ::pet_robot_ros::SensorData > SensorDataPtr;
typedef boost::shared_ptr< ::pet_robot_ros::SensorData const> SensorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::SensorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::SensorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pet_robot_ros::SensorData_<ContainerAllocator1> & lhs, const ::pet_robot_ros::SensorData_<ContainerAllocator2> & rhs)
{
  return lhs.touch_detected == rhs.touch_detected &&
    lhs.distance == rhs.distance &&
    lhs.temperature == rhs.temperature &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pet_robot_ros::SensorData_<ContainerAllocator1> & lhs, const ::pet_robot_ros::SensorData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::SensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::SensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::SensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::SensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::SensorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::SensorData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::SensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a89da8b484867ca2bc71805d9719a4d";
  }

  static const char* value(const ::pet_robot_ros::SensorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a89da8b484867caULL;
  static const uint64_t static_value2 = 0x2bc71805d9719a4dULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::SensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/SensorData";
  }

  static const char* value(const ::pet_robot_ros::SensorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::SensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Sensor data from robot\n"
"bool touch_detected\n"
"float32 distance  # cm\n"
"float32 temperature  # Celsius\n"
"time timestamp\n"
;
  }

  static const char* value(const ::pet_robot_ros::SensorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::SensorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.touch_detected);
      stream.next(m.distance);
      stream.next(m.temperature);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::SensorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pet_robot_ros::SensorData_<ContainerAllocator>& v)
  {
    s << indent << "touch_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.touch_detected);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_SENSORDATA_H
