// Generated by gencpp from file pet_robot_ros/SetEmotion.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_SETEMOTION_H
#define PET_ROBOT_ROS_MESSAGE_SETEMOTION_H

#include <ros/service_traits.h>


#include <pet_robot_ros/SetEmotionRequest.h>
#include <pet_robot_ros/SetEmotionResponse.h>


namespace pet_robot_ros
{

struct SetEmotion
{

typedef SetEmotionRequest Request;
typedef SetEmotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEmotion
} // namespace pet_robot_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pet_robot_ros::SetEmotion > {
  static const char* value()
  {
    return "b4511e9a0d7a1edc71467ea13a9b50a5";
  }

  static const char* value(const ::pet_robot_ros::SetEmotion&) { return value(); }
};

template<>
struct DataType< ::pet_robot_ros::SetEmotion > {
  static const char* value()
  {
    return "pet_robot_ros/SetEmotion";
  }

  static const char* value(const ::pet_robot_ros::SetEmotion&) { return value(); }
};


// service_traits::MD5Sum< ::pet_robot_ros::SetEmotionRequest> should match
// service_traits::MD5Sum< ::pet_robot_ros::SetEmotion >
template<>
struct MD5Sum< ::pet_robot_ros::SetEmotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pet_robot_ros::SetEmotion >::value();
  }
  static const char* value(const ::pet_robot_ros::SetEmotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pet_robot_ros::SetEmotionRequest> should match
// service_traits::DataType< ::pet_robot_ros::SetEmotion >
template<>
struct DataType< ::pet_robot_ros::SetEmotionRequest>
{
  static const char* value()
  {
    return DataType< ::pet_robot_ros::SetEmotion >::value();
  }
  static const char* value(const ::pet_robot_ros::SetEmotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pet_robot_ros::SetEmotionResponse> should match
// service_traits::MD5Sum< ::pet_robot_ros::SetEmotion >
template<>
struct MD5Sum< ::pet_robot_ros::SetEmotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pet_robot_ros::SetEmotion >::value();
  }
  static const char* value(const ::pet_robot_ros::SetEmotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pet_robot_ros::SetEmotionResponse> should match
// service_traits::DataType< ::pet_robot_ros::SetEmotion >
template<>
struct DataType< ::pet_robot_ros::SetEmotionResponse>
{
  static const char* value()
  {
    return DataType< ::pet_robot_ros::SetEmotion >::value();
  }
  static const char* value(const ::pet_robot_ros::SetEmotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_SETEMOTION_H
