// Generated by gencpp from file pet_robot_ros/SetEmotionRequest.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_SETEMOTIONREQUEST_H
#define PET_ROBOT_ROS_MESSAGE_SETEMOTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pet_robot_ros
{
template <class ContainerAllocator>
struct SetEmotionRequest_
{
  typedef SetEmotionRequest_<ContainerAllocator> Type;

  SetEmotionRequest_()
    : emotion()
    , intensity(0.0)  {
    }
  SetEmotionRequest_(const ContainerAllocator& _alloc)
    : emotion(_alloc)
    , intensity(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _emotion_type;
  _emotion_type emotion;

   typedef float _intensity_type;
  _intensity_type intensity;





  typedef boost::shared_ptr< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetEmotionRequest_

typedef ::pet_robot_ros::SetEmotionRequest_<std::allocator<void> > SetEmotionRequest;

typedef boost::shared_ptr< ::pet_robot_ros::SetEmotionRequest > SetEmotionRequestPtr;
typedef boost::shared_ptr< ::pet_robot_ros::SetEmotionRequest const> SetEmotionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator1> & lhs, const ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.emotion == rhs.emotion &&
    lhs.intensity == rhs.intensity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator1> & lhs, const ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55951f00a9a7dc87dad4cca95af9a536";
  }

  static const char* value(const ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55951f00a9a7dc87ULL;
  static const uint64_t static_value2 = 0xdad4cca95af9a536ULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/SetEmotionRequest";
  }

  static const char* value(const ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request to set robot's emotion\n"
"string emotion  # happy, sad, anxious, stressed, tired, angry, neutral\n"
"float32 intensity  # 0.0 to 1.0\n"
;
  }

  static const char* value(const ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.emotion);
      stream.next(m.intensity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEmotionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pet_robot_ros::SetEmotionRequest_<ContainerAllocator>& v)
  {
    s << indent << "emotion: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.emotion);
    s << indent << "intensity: ";
    Printer<float>::stream(s, indent + "  ", v.intensity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_SETEMOTIONREQUEST_H
