// Generated by gencpp from file pet_robot_ros/SetEmotionResponse.msg
// DO NOT EDIT!


#ifndef PET_ROBOT_ROS_MESSAGE_SETEMOTIONRESPONSE_H
#define PET_ROBOT_ROS_MESSAGE_SETEMOTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pet_robot_ros
{
template <class ContainerAllocator>
struct SetEmotionResponse_
{
  typedef SetEmotionResponse_<ContainerAllocator> Type;

  SetEmotionResponse_()
    : success(false)
    , message()  {
    }
  SetEmotionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetEmotionResponse_

typedef ::pet_robot_ros::SetEmotionResponse_<std::allocator<void> > SetEmotionResponse;

typedef boost::shared_ptr< ::pet_robot_ros::SetEmotionResponse > SetEmotionResponsePtr;
typedef boost::shared_ptr< ::pet_robot_ros::SetEmotionResponse const> SetEmotionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator1> & lhs, const ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator1> & lhs, const ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pet_robot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pet_robot_ros/SetEmotionResponse";
  }

  static const char* value(const ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEmotionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pet_robot_ros::SetEmotionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PET_ROBOT_ROS_MESSAGE_SETEMOTIONRESPONSE_H
